version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.8.1

    working_directory: ~/combobo

    steps:
      - checkout

      - run: npm install

      # run tests!
      - run: npm test
